# Generated by Django 3.0.4 on 2020-03-19 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(unique=True, verbose_name='Адрес')),
                ('built', models.IntegerField(verbose_name='Год постройки')),
            ],
            options={
                'verbose_name': 'Строение',
                'verbose_name_plural': 'Строение',
                'db_table': 'construction_buildings',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bricks_amount', models.IntegerField(verbose_name='Количество кирпичей')),
                ('execution_time', models.DateTimeField(verbose_name='Время выполнения')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='construction.Building', verbose_name='Строение')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'db_table': 'construction_jobs',
            },
        ),
    ]
